<a href="https://colab.research.google.com/github/yesdeepakmittal/pytraining/blob/master/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import math

In [4]:
print(math.sqrt(25))
print(math.pi)

5.0
3.141592653589793


<h2>⭐Numpy</h2>

In [10]:
zero_matrix = np.zeros(3)
print(zero_matrix)

print('\n')

zero_matrix = np.zeros((3,3))
print(zero_matrix)

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

print('\n')

print('Transposed Matrix\n',matrix.T)

[[1 2 3 4]
 [5 6 7 8]]


Transposed Matrix
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [16]:
print(matrix[1,1]) #Accessing (1,1)th element

6


In [17]:
print(np.shape(matrix))

(2, 4)


In [21]:
print('The sum of columns of a matrix:',sum(matrix))

The sum of columns of a matrix: [ 6  8 10 12]


In [26]:
print('The sum of first row:',np.sum(matrix[0]))
print('The sum of second row:',np.sum(matrix[1]))

print('\n')

print('The sum of first column:',np.sum(matrix,axis=0)[0])
print('The sum of first column:',sum(matrix)[0])

The sum of first row: 10
The sum of second row: 26


The sum of first column: 6
The sum of first column: 6


In [22]:
print('The sum of entire matrix:',np.sum(matrix))

The sum of entire matrix: 36


In [28]:
print(matrix)

[[1 2 3 4]
 [5 6 7 8]]


<h2>⭐Pandas</h2>

In [30]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a = pd.DataFrame(a)
a

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [32]:
print('The dataframe has {} rows and {} columns'.format(a.shape[0],a.shape[1]))

The dataframe has 3 rows and 4 columns


In [33]:
a.columns

RangeIndex(start=0, stop=4, step=1)

In [34]:
for i in a.columns:
    print(i)

0
1
2
3


In [36]:
a.columns = list('abcd')
a

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [37]:
a['a'].sum()

15

In [38]:
a.describe()

a     b     c     d
count  3.0   3.0   3.0   3.0
mean   5.0   6.0   7.0   8.0
std    4.0   4.0   4.0   4.0
min    1.0   2.0   3.0   4.0
25%    3.0   4.0   5.0   6.0
50%    5.0   6.0   7.0   8.0
75%    7.0   8.0   9.0  10.0
max    9.0  10.0  11.0  12.0

In [39]:
a.head(1)

a  b  c  d
0  1  2  3  4

In [40]:
a.tail(1)

a   b   c   d
2  9  10  11  12

In [41]:
a.sample(1)

a   b   c   d
2  9  10  11  12

In [42]:
a['a'].unique()

array([1, 5, 9])

In [43]:
a['e'] = 0
a

a   b   c   d  e
0  1   2   3   4  0
1  5   6   7   8  0
2  9  10  11  12  0

In [45]:
a.loc[1:2,['a','b']]

a   b
1  5   6
2  9  10

In [46]:
a.iloc[1,1]

6

In [48]:
a['a'].value_counts()

9    1
5    1
1    1
Name: a, dtype: int64

In [49]:
a.T

0  1   2
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12
e  0  0   0