<a href="https://colab.research.google.com/github/yesdeepakmittal/pytraining/blob/master/Advanced/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
zero_matrix = np.zeros(3)
print(zero_matrix)

print('\n')

zero_matrix = np.zeros((3,3))
print(zero_matrix)

[0. 0. 0.]


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((3,3,3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [ ]:
matrix = np.array([[1,2,3,4],[5,6,7,8]])
print(matrix)

print()

print('Transposed Matrix\n',matrix.T)

[[1 2 3 4]
 [5 6 7 8]]

Transposed Matrix
 [[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [ ]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(matrix[1,1]) #Accessing (1,1)th element

6


In [ ]:
print(np.shape(matrix))

(2, 4)


In [ ]:
matrix.shape

(2, 4)

In [ ]:
print('The sum of columns of a matrix:',sum(matrix))

The sum of columns of a matrix: [ 6  8 10 12]


In [ ]:
print('The sum of first row:',np.sum(matrix[0]))
print('The sum of second row:',np.sum(matrix[1]))

print('\n')

print('The sum of first column:',np.sum(matrix,axis=0)[0])
print('The sum of first column:',sum(matrix)[0])

The sum of first row: 10
The sum of second row: 26


The sum of first column: 6
The sum of first column: 6


In [ ]:
# sum() vs np.sum()

print(sum(matrix))  #perform sum column-wise

print('The sum of entire matrix:',np.sum(matrix))   #perform sum of entire matrix

[ 6  8 10 12]
The sum of entire matrix: 36


In [ ]:
print(np.random.rand(15))

[0.9452449  0.95842464 0.18131936 0.91683323 0.88795515 0.20460359
 0.41336306 0.44789265 0.74109842 0.35186782 0.99536278 0.7955444
 0.02575158 0.0923094  0.68666052]


In [ ]:
np.random.rand(3,3)

array([[0.57899906, 0.71892703, 0.19078916],
       [0.69755767, 0.88563007, 0.89301205],
       [0.78873038, 0.97861938, 0.34097149]])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.linspace(0,5,11)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
a = [1,2,3,4]
np.repeat(a,2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
np.tile(a,2)

array([1, 2, 3, 4, 1, 2, 3, 4])

In [ ]:
#Identity matrix 
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
diag = np.random.randint(low = 1,high = 10, size = 9)
diag

array([5, 2, 4, 4, 6, 2, 8, 1, 5])

In [ ]:
diag_new = np.reshape(diag, (3,3))
diag_new

array([[5, 2, 4],
       [4, 6, 2],
       [8, 1, 5]])

In [ ]:
diag_new.flatten()

array([5, 2, 4, 4, 6, 2, 8, 1, 5])

In [ ]:
np.unique(diag_new.flatten())

array([1, 2, 4, 5, 6, 8])

In [ ]:
np.unique(diag_new.flatten(),return_counts=True)

(array([1, 2, 4, 5, 6, 8]), array([1, 2, 2, 2, 1, 1], dtype=int64))

In [ ]:
np.unique(diag_new.flatten(),return_index=True)

(array([1, 2, 4, 5, 6, 8]), array([7, 1, 2, 0, 4, 6], dtype=int64))

In [ ]:
np.append(diag_new.flatten(),[10,11])

array([ 5,  2,  4,  4,  6,  2,  8,  1,  5, 10, 11])

In [ ]:
np.insert(diag_new.flatten(),0,[22,33])

array([22, 33,  5,  2,  4,  4,  6,  2,  8,  1,  5])

In [ ]:
diag_new.flatten()

array([5, 2, 4, 4, 6, 2, 8, 1, 5])

In [ ]:
np.delete(diag_new.flatten(),[1,2])

array([5, 4, 6, 2, 8, 1, 5])

In [ ]:
temp = np.array([1,2,3,3])
temp_copy = temp.copy()
temp_copy

array([1, 2, 3, 3])

In [ ]:
temp1 = np.array([[10,20,30],[40,50,60]])
temp2 = np.array([[5,15,25],[35,45,55]])

np.concatenate((temp1,temp2),axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [ 5, 15, 25],
       [35, 45, 55]])

In [ ]:
np.vstack((temp1,temp2))

array([[10, 20, 30],
       [40, 50, 60],
       [ 5, 15, 25],
       [35, 45, 55]])

In [ ]:
np.concatenate((temp1,temp2),axis=1)

array([[10, 20, 30,  5, 15, 25],
       [40, 50, 60, 35, 45, 55]])

In [ ]:
np.hstack((temp1,temp2))

array([[10, 20, 30,  5, 15, 25],
       [40, 50, 60, 35, 45, 55]])

In [ ]:
np.intersect1d([1,2,3,4],[2,4,6,8])

array([2, 4])

In [ ]:
np.union1d([1,2,3,4],[2,4,6,8])

array([1, 2, 3, 4, 6, 8])

In [ ]:
np.setdiff1d([1,2,3,4],[2,4,6,8])

array([1, 3])

In [ ]:
np.setxor1d([1,2,3,4],[2,4,6,8])

array([1, 3, 6, 8])

In [ ]:
diag_new

array([[8, 1, 3],
       [6, 5, 6],
       [2, 8, 3]])

In [ ]:
np.diag(diag_new)

array([8, 5, 3])

In [ ]:
diag_new.ndim

2

In [ ]:
diag_new.size

9

In [ ]:
diag_new.shape

(3, 3)

In [ ]:
diag_new

array([[8, 1, 3],
       [6, 5, 6],
       [2, 8, 3]])

In [ ]:
diag_new + 10

array([[18, 11, 13],
       [16, 15, 16],
       [12, 18, 13]])

In [ ]:
diag_new - 10

array([[-2, -9, -7],
       [-4, -5, -4],
       [-8, -2, -7]])

In [ ]:
diag_new * 10

array([[80, 10, 30],
       [60, 50, 60],
       [20, 80, 30]])

In [ ]:
diag_new / 2

array([[4. , 0.5, 1.5],
       [3. , 2.5, 3. ],
       [1. , 4. , 1.5]])

In [ ]:
diag_new // 2 

array([[4, 0, 1],
       [3, 2, 3],
       [1, 4, 1]])

In [ ]:
diag_new

array([[8, 1, 3],
       [6, 5, 6],
       [2, 8, 3]])

In [ ]:
np.sort(diag_new)

array([[1, 3, 8],
       [5, 6, 6],
       [2, 3, 8]])

In [ ]:
# Exponential 
np.exp(diag_new)

array([[2.98095799e+03, 2.71828183e+00, 2.00855369e+01],
       [4.03428793e+02, 1.48413159e+02, 4.03428793e+02],
       [7.38905610e+00, 2.98095799e+03, 2.00855369e+01]])

In [ ]:
np.log(diag_new) #natural log

array([[2.07944154, 0.        , 1.09861229],
       [1.79175947, 1.60943791, 1.79175947],
       [0.69314718, 2.07944154, 1.09861229]])

In [ ]:
np.log10(diag_new)

array([[0.90308999, 0.        , 0.47712125],
       [0.77815125, 0.69897   , 0.77815125],
       [0.30103   , 0.90308999, 0.47712125]])

In [ ]:
np.log2(diag_new)

array([[3.        , 0.        , 1.5849625 ],
       [2.5849625 , 2.32192809, 2.5849625 ],
       [1.        , 3.        , 1.5849625 ]])

In [ ]:
np.log([10,np.e,100,np.e**2,np.inf])

array([2.30258509, 1.        , 4.60517019, 2.        ,        inf])

In [ ]:
np.log10([10,np.e,100,np.e**2,np.inf])

array([1.        , 0.43429448, 2.        , 0.86858896,        inf])

In [ ]:
np.sin(diag_new)

array([[ 0.98935825,  0.84147098,  0.14112001],
       [-0.2794155 , -0.95892427, -0.2794155 ],
       [ 0.90929743,  0.98935825,  0.14112001]])

In [ ]:
np.cos(diag_new)

array([[-0.14550003,  0.54030231, -0.9899925 ],
       [ 0.96017029,  0.28366219,  0.96017029],
       [-0.41614684, -0.14550003, -0.9899925 ]])

In [ ]:
np.tan(diag_new)

array([[-6.79971146,  1.55740772, -0.14254654],
       [-0.29100619, -3.38051501, -0.29100619],
       [-2.18503986, -6.79971146, -0.14254654]])

In [ ]:
diag_new

array([[8, 1, 3],
       [6, 5, 6],
       [2, 8, 3]])

In [ ]:
np.sum(diag_new)

42

In [ ]:
np.sum(diag_new,axis = 0)

array([16, 14, 12])

In [ ]:
np.sum(diag_new,axis = 1)

array([12, 17, 13])

In [ ]:
np.min(diag_new)

1

In [ ]:
np.max(diag_new)

8

In [ ]:
np.mean(diag_new)

4.666666666666667

In [ ]:
np.median(diag_new)

5.0

In [ ]:
np.std(diag_new)

2.4037008503093262

In [ ]:
np.var(diag_new)

5.777777777777779

In [ ]:
np.abs(diag_new)

array([[8, 1, 3],
       [6, 5, 6],
       [2, 8, 3]])

<h2>⭐Pandas</h2>

In [ ]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
a = pd.DataFrame(a)
a

0   1   2   3
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
print('The dataframe has {} rows and {} columns'.format(a.shape[0],a.shape[1]))

The dataframe has 3 rows and 4 columns


In [ ]:
a.columns

RangeIndex(start=0, stop=4, step=1)

In [ ]:
for i in a.columns:
    print(i)

0
1
2
3


In [ ]:
a.columns = list('abcd')
a

a   b   c   d
0  1   2   3   4
1  5   6   7   8
2  9  10  11  12

In [ ]:
a['a'].sum()

15

In [ ]:
a.describe()

a     b     c     d
count  3.0   3.0   3.0   3.0
mean   5.0   6.0   7.0   8.0
std    4.0   4.0   4.0   4.0
min    1.0   2.0   3.0   4.0
25%    3.0   4.0   5.0   6.0
50%    5.0   6.0   7.0   8.0
75%    7.0   8.0   9.0  10.0
max    9.0  10.0  11.0  12.0

In [ ]:
a.head(1)

a  b  c  d
0  1  2  3  4

In [ ]:
a.tail(1)

a   b   c   d
2  9  10  11  12

In [ ]:
a.sample(1)

a  b  c  d
0  1  2  3  4

In [ ]:
a['a'].unique()

array([1, 5, 9])

In [ ]:
a['e'] = 0
a

a   b   c   d  e
0  1   2   3   4  0
1  5   6   7   8  0
2  9  10  11  12  0

In [ ]:
a.loc[1:2,['a','b']]

a   b
1  5   6
2  9  10

In [ ]:
a.iloc[1,1]

6

In [ ]:
a['a'].value_counts()

9    1
5    1
1    1
Name: a, dtype: int64

In [ ]:
a.T

0  1   2
a  1  5   9
b  2  6  10
c  3  7  11
d  4  8  12
e  0  0   0

In [ ]:
df = pd.DataFrame(
    np.random.randn(10, 5),
    columns=('col %d' % i for i in range(5)))